baseURL = 'https://miguoliang.com/net_value'
languageCode = 'zh_CN'
title = '产品净值 | 禅宽量化'
theme = 'hugo-coder'

[params]
author = "禅宽量化"
keywords = "股票,期货,期权,基金,量化交易"

[params.googleTagManager]
id = "G-3XTC5Q3D4Y"